spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: svc_user
    password: svc_password
    driver-class-name: com.mysql.cj.jdbc.Driver