server:
  port: 6060
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: password
            # redirect url: http://localhost:8080/login/oauth2/code/google
          github:
            client-id: test
            client-secret: password
