server:
  port: 6060
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: password
            # redirect url: http://localhost:8080/login/oauth2/code/google
          github:
            client-id: test
            client-secret: password
          my_authorization_server:
            client-name: my server
            client-id: client2
            client-secret: secret2
            provider: my_authorization_server
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:6060/login/oauth2/code/my_authorization_server
            scope:
              - openid

        provider:
          my_authorization_server:
            issuer-uri: http://127.0.0.1:8080

logging:
  level:
    org.springframework.security: TRACE