server:
  port: 9090

application:
  security:
    # authorization server: http://localhost:8080/.well-known/openid-configuration
    key-set-uri: http://localhost:8080/oauth2/jwks
    introspection-uri: http://localhost:8080/oauth2/introspect
    resource-server:
      client-id: resource_server
      client-secret: resource_server_secret
